version: '3'

services: 
  app:
    build: .
    container_name: api-send-email
    # entrypoint: dockerize -wait tcp://redis:6379 -timeout 20s docker-entrypoint.sh
    networks:
      - redis-network
    ports:
      - 3334:3334
    # volumes:
    #   - .:/home/node/app
    tty: true
    depends_on: 
      - redis
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - redis-network
networks: 
  redis-network:
    driver: bridge
